###
GET http://localhost:9090/people/

###
DELETE http://localhost:9090/people/

###
POST http://localhost:9090/people/
Content-Type: application/json

{
  "name":{
    "firstname" : "firstname",
    "middlename": "middlename",
    "lastname": "lastname"
  },
  "age":  29,
  "nationality": "TR"
}

###
POST http://localhost:9090/people/firstname
Content-Type: application/json

{
  "name":{
    "firstname" : "firstnameUpdate",
    "middlename": "middlenameUpdate",
    "lastname": "lastnameUpdate"
  },
  "age":  49,
  "nationality": "DE"
}